### ISSUE TITLE
Plugin is massively out of date

### ISSUE THREAD

**Issue by Codingale** [dequeues/MyBB-CloudFlare-Manager#12]
Few thing's I've noticed:

- **https://www.cloudflare.com/cloudflare-settings.html?z=domain.tld** has changed to **https://www.cloudflare.com/a/overview/domain.tld**
- Name servers don't seem to be detected.

**Comment by dequeues** [comment]
Of course, it's not been maintained for a long time. I will get these resolved when I am home though.

**Comment by Codingale** [comment]
Oh, by the way about the name server function. I ran the source code, and it returns true, but for some reason in the class/case it doesn't seem to so something about the function is strange. I haven't looked deep into it.

**Comment by dequeues** [comment]
Only now looking into this (sorry!). I'm not sure what you mean about the nameserver, it seems to be fine? What nameservers are you using?

**Comment by Codingale** [comment]
```
olga.ns.cloudflare.com
woz.ns.cloudflare.com
```

**Comment by dequeues** [comment]
Could you provide me a domain? I can't replicate.

**Comment by Codingale** [comment]
`canadiansturf.cf` with I'm pretty sure the latest version of MyBB, it possibly could have been my host I'm not sure. I hacked the function to return true always.

**Comment by dequeues** [comment]
It returns true for me when I run the function with your domain.

**Comment by Codingale** [comment]
Probably my host, let's just ignore that part of it. Are the other things fixed? I believe the API changed too but not sure.

**Comment by dequeues** [comment]
I've tested all the features and they seem to work. I'll close this for now.
