### ISSUE TITLE
View/Modify Link Bad - Cloudflare Manager Pluggin

### ISSUE THREAD

**Issue by 41KABMax** [dequeues/MyBB-CloudFlare-Manager#18]
The View/Modify link on the Cloudflare Manager tab does not point to a valid page.

https://dash.cloudflare.com/overview/[mydomain] results in a 404 error page:
"404 | We can't find the page you're looking for."

The correct format of the URL for the Cloudfare Dashboard for my site is:
https://dash.cloudflare.com/[hash]/[mydomain]

**Comment by dequeues** [comment]
I'll take a look into this soon (probably tomorrow). I think I can get the hash from the zone ID API request, though I would need to double check.

**Comment by 41KABMax** [comment]
I really appreciate it.  Thanks for looking into it!

**Comment by 41KABMax** [comment]
Beautiful!
    Works perfectly.  Thank you!
    BFesko
