### ISSUE TITLE
Cloudflare Compatibility Issue on MyBB 1.8.6

### ISSUE THREAD

**Issue by johndave9296** [dequeues/MyBB-CloudFlare-Manager#6]
Hi. I tried to use your plugin cloudflare into my site but when I went to the plugins page it saids that plugin is incompatible with mybb 1.8.6 :(

**Comment by dequeues** [comment]
@jaydee9296 - Try https://github.com/dequeues/MyBB-CloudFlare-Manager/commit/f119951fc1ee9dd883a20d4b46af9983dbf87318

**Comment by johndave9296** [comment]
I tried and returned with this error.

![vpnpinas10](https://cloud.githubusercontent.com/assets/8472952/13095340/0543f4d2-d54c-11e5-8881-fa941fc7e58b.PNG)

**Comment by dequeues** [comment]
@jaydee9296 Should be fixed in https://github.com/dequeues/MyBB-CloudFlare-Manager/commit/0f6affcd119dbfb7ea261877e1b5658643eac28a
