### ISSUE TITLE
Error on Postbit Cloudflare Spam

### ISSUE THREAD

**Issue by johndave9296** [dequeues/MyBB-CloudFlare-Manager#7]
Having this error though in cloudflare... Is there a solution for it?

![forum22](https://cloud.githubusercontent.com/assets/8472952/13206040/0e1a8b96-d931-11e5-9575-6bd690fdfe94.PNG)

**Comment by dequeues** [comment]
This feature does not even work. I'll remove it. In process.

**Comment by dequeues** [comment]
Removed in https://github.com/dequeues/MyBB-CloudFlare-Manager/commit/dc5934b1fd4234d38778fe5fc403af03e596e03b

**Comment by johndave9296** [comment]
Thanks! :D
